ci:
  autofix_prs: false
  autoupdate_schedule: quarterly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: no-commit-to-branch
  - id: debug-statements
  - id: check-merge-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-shebang-scripts-are-executable
  - id: check-executables-have-shebangs
  - id: check-toml

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.2.0
  hooks:
  - id: mypy
    pass_filenames: false
    entry: mypy
    args: [--ignore-missing-imports, --no-strict-optional, --no-implicit-optional, --explicit-package-bases, --namespace-packages, --exclude, submodules/, --exclude, figures/, --exclude, 3Phase, .]
    additional_dependencies: [types-requests >= 2.28.0]

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    language_version: python3.10

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.8.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/python-poetry/poetry
  rev: 1.4.0
  hooks:
  - id: poetry-check
  - id: poetry-lock
    args: [--no-update, --check]
  - id: poetry-export
    args: [--without-hashes, --output, requirements/requirements.txt]
